### PR TITLE
did:web support

### PR DESCRIPTION
**Pull request by stuartf**
Here's a first pass at getting did:web working. I'm not sure how scalable this approach is for supporting more DID methods in the future, but also not sure if that's planned.

I still need to see if this actually works and add some tests, but wanted to get feedback before going further.

### CODE REVIEW

**Review by jchartrand — COMMENTED** [review]
It looks great! 

I think you and I had talked a few months ago about how the tenants are setup in the .env and whether there might be some better way to set the tenant info. 

I think we'd left it that it is a tricky problem, given that we'd probably ideally like to stick with using plain old environment variables (rather than reading from some other file), but if since then you've see any way to restructure how the configuration of the tenants works, please do tell!

**Comment by stuartf** [comment]
Great, I'll continue on this track then. Unfortunately, I haven't found a better way to handle configuration, I considered doing something like:

```
TENANT_EXAMPLE_CONF='{"url": "https://example.com", "didSeed": "123abc", "didMethod": "web"}'
```

And then JSON.parse()ing that, but it wouldn't be backward compatible to current configs and is potentially even more of a mess.

**Comment by stuartf** [comment]
@jchartrand I've updated the README and added some tests, so this should be ready for review now

**Comment by dmitrizagidulin** [comment]
Nice!! @stuartf we'll take a look!

**Review by jchartrand — APPROVED** [review]
Looks great!

**Pull request merged**
