### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by stuartf**
This should:
 - setup linting to match the isomorphic-lib-template
 -  get all code into compliance
 - make a pre-commit hook to:
   -  check any staged files for lint errors
   - run all unit tests

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
👍 thanks for doing this, @stuartf !

**Comment by sembrat** [comment]
@dmitrizagidulin how would you like us to continue with this? Would you like us to rebase and commit, or is that something the DCC would like to lead on?

**Comment by jchartrand** [comment]
@stuartf Hey Stuart, did you want to merge it in to main?

**Comment by stuartf** [comment]
@jchartrand sure, I can merge this myself, I just didn't want to step on any toes if that wasn't the way you expected it to happen.

**Comment by jchartrand** [comment]
@stuartf Is it okay with you if I squash the 5 commits and then merge?

**Comment by stuartf** [comment]
@jchartrand yes, I'm fine with you squashing the commits and merging, go for it

**Pull request merged**
